---
- name: Install IIS Web Server
  hosts: windows
  tasks:

    - name: Install IIS (Web-Server only)
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Install IIS (Web-Server and Web-Common-Http)
      ansible.windows.win_feature:
        name:
        - Web-Server
        - Web-Common-Http
        state: present

    - name: Disable Windows Firewall
      community.windows.win_firewall:
        state: disabled
        profiles:
        - Domain
        - Private
        - Public

    - name: Create website index.html
      win_copy:
        content: "Windows Server"
        dest: C:\Inetpub\wwwroot\index.html

    - name: Reboot if installing Web-Server feature requires it
      ansible.windows.win_reboot:
      when: win_feature.reboot_required
