---
- name: Install and start Apache Web Server on RHEL OS
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: Install firewalld
    ansible.builtin.dnf:
      name: firewalld
      state: latest

  - name: Install php
    ansible.builtin.dnf:
      name:
        - php
        - php-fpm
        - php-mysqlnd
        - php-opcache
        - php-gd
        - php-xml
        - php-mbstring

  - name: Install httpd-tools
    ansible.builtin.dnf:
      name: httpd-tools
      state: latest

  - name: Ensure httpd is running
    service:
      name: httpd
      state: started
      enabled: true

  - name: Start and enable php-fpm
    service:
      name: php-fpm
      state: started
      enabled: true

  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Open port 443 for https access
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: Add content to index.html
    copy:
      content: "Welcome to the Apache Server"
      dest: /var/www/html/index.html

  - name: Add php content
    copy:
      content: "Hi" 
      dest: /var/www/html/info.php
