---
- name: Manage the state of Windows/RHEL Web Services
  hosts: mixed_web_servers
  gather_facts: true

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print OS Type
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Set Windows specific value for service variable
      set_fact:
        service: W3Svc
      when: 'ansible_distribution == "Microsoft Windows Server 2019 Datacenter" and service_survey == "web service"'

    - name: Set RHEL specific value for service variable
      set_fact:
        service: httpd
      when: 'ansible_distribution == "RedHat" and service_survey == "web service"'

    - name: Set Windows specific value for mode variable
      set_fact:
        mode: auto
      when: 'mode_survey == "yes" and ansible_distribution == "Microsoft Windows Server 2019 Datacenter"'

    - name: Set Windows specific value for mode variable
      set_fact:
        mode: manual
      when: 'mode_survey == "no" and ansible_distribution == "Microsoft Windows Server 2019 Datacenter"'

    - name: Set service startup mode and current state
      win_service:
        name: "{{ service }}"
        start_mode: "{{ mode }}"
        state: "{{ service_state }}"
        force_dependent_services: yes
      when: 'ansible_distribution == "Microsoft Windows Server 2019 Datacenter"'

    - name: Set service startup mode and current state
      service:
        name: "{{ service }}"
        state: "{{ service_state }}"
        enabled: "{{ mode_survey }}"
      become: yes
      when: 'ansible_distribution == "RedHat"'

