---
- name: Manage the state of Windows/RHEL Web Services
  hosts: mixed_web_servers
  connection: local
  gather_facts: true

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print OS Type
      ansible.builtin.debug:
        var: ansible_distribution

    - name: Set Windows specific value for service variable
      set_fact:
        service: W3Svc
      when: '"Windows" in ansible_distribution and service_survey == "web service"'

    - name: Set RHEL specific value for service variable
      set_fact:
        service: httpd
      when: '"RedHat" in ansible_distribution and service_survey == "web service"'

    - name: Set Windows specific value for mode variable
      set_fact:
        mode: auto
      when: 'mode_survey == "yes" and "Windows" in ansible_distribution'

    - name: Set Windows specific value for mode variable
      set_fact:
        mode: manual
      when: 'mode_survey == "no" and "Windows" in ansible_distribution'

    - name: Set service startup mode and current state
      win_service:
        name: "{{ service }}"
        start_mode: "{{ mode }}"
        state: "{{ service_state }}"
        force_dependent_services: yes
      when: '"Windows" in ansible_distribution'

    - name: Set service startup mode and current state
      service:
        name: "{{ service }}"
        state: "{{ service_state }}"
        enabled: "{{ mode_survey }}"
      become: yes
      when: '"RedHat" in ansible_distribution'

